#/home/rafael/ANSIBLE/SW-TEMPLATE
---
- name: Generate router configuration files
  hosts: local

  roles:
   - access_switch
   
   
#/home/rafael/ANSIBLE/SW-TEMPLATE/roles/access_switch/tasks
---
- name: Generate configuration files
  template: src=access_switch.j2 dest=/home/rafael/ANSIBLE/SW-TEMPLATE/CFGS/{{item.hostname}}.txt
  with_items: switches


#/home/rafael/ANSIBLE/SW-TEMPLATE/roles/access_switch/templates
service timestamps debug datetime msec localtime show-timezone
service timestamps log datetime msec localtime show-timezone
!
hostname {{item.hostname}}
!
logging buffered 32000
no logging console
enable secret 0 {{item.secret}}
!
!
!
!
interface FastEthernet0/1
 switchport access vlan {{item.access_vlan}}
 switchport mode access
 spanning-tree portfast
!
interface FastEthernet0/24
 switchport access vlan {{item.access_vlan}}
 switchport mode access
 spanning-tree portfast
!
interface Vlan1
 ip address {{item.ip_addr}} 255.255.255.0
 no ip route-cache
!
ip default-gateway {{item.default_gateway}}
snmp-server community {{item.snmp_community}} RO
!
{%if item.SNMPV3%}
access-list 98 remark *** SNMP ***
access-list 98 permit any
!
snmp-server view VIEWSTD iso included
snmp-server group READONLY v3 priv read VIEWSTD access 98
snmp-server user pysnmp READONLY v3 auth sha auth_key priv aes 128 encrypt_key
{%endif%}
 
!
line con 0
line vty 0 4
 login
line vty 5 15
 login
!
!
end


#/home/rafael/ANSIBLE/SW-TEMPLATE/roles/access_switch/vars
---
switches:
  - {hostname: access-sw1, secret: my_secret, ip_addr: 1.1.1.10, SNMPV3: True, 
     default_gateway: 1.1.1.1, access_vlan: 1, snmp_community: my_snmp}
  - {hostname: access-sw2, secret: my_secret, ip_addr: 1.1.2.10, SNMPV3: False, 
     default_gateway: 1.1.2.1, access_vlan: 2, snmp_community: my_snmp}
  - {hostname: access-sw3, secret: my_secret, ip_addr: 1.1.3.10, SNMPV3: True,
     default_gateway: 1.1.3.1, access_vlan: 3, snmp_community: my_snmp}
  - {hostname: access-sw4, secret: my_secret, ip_addr: 1.1.4.10, SNMPV3: True, 
     default_gateway: 1.1.4.1, access_vlan: 4, snmp_community: my_snmp}
  - {hostname: access-sw5, secret: my_secret, ip_addr: 1.1.5.10, SNMPV3: True,
     default_gateway: 1.1.5.1, access_vlan: 5, snmp_community: my_snmp}
