---

#1. Using Ansible, configure three VLANs on the Arista switch specifying both the VLAN IDs and the VLAN names.  
#For the VLAN IDs randomly pick three numbers between 100 and 999.

- name: exercise1
  hosts: arista

  tasks:
    - name: Create three vlans
      eos_vlan: name={{item.vlan_name}} vlanid={{item.vlan_id}}
            eapi_username={{eapi_username}}
            eapi_password={{eapi_password}}
            eapi_hostname={{eapi_hostname}}
            eapi_port={{eapi_port}}
      with_items:
        - {vlan_name: network110, vlan_id: 110}
        - {vlan_name: network120, vlan_id: 120}
        - {vlan_name: network130, vlan_id: 130}
