---

#2. Use Ansible to configure your 'primary Ethernet interface' as follows:
#interface description:  *** IN USE ***
#switchport mode:        access
#VLAN:                   <one of the VLANs created in exercise1>
#Your 'primary Ethernet interface' is specified in your ~/ansible-hosts file.
#If your primary interface is already 'IN USE' (by someone else), then use your secondary interface
# (once again specified in ~/ansible-hosts).  You can determine if an interface is already in use by 
# SSH'ing into the switch. Reminder, do NOT use Ethernet1.

- name: Exercise2
  hosts: arista

  tasks:
    - name: Set Ethernet3 description
      eos_interface: name=Ethernet3 description="*** IN USE ***"
            eapi_username={{eapi_username}}
            eapi_password={{eapi_password}}
            eapi_hostname={{eapi_hostname}}
            eapi_port={{eapi_port}}

    - name: Set Ethernet3 to access mode and on vlan 130
      eos_switchport: name=Ethernet3 mode=access access_vlan=130 trunk_allowed_vlans=all
            eapi_username={{eapi_username}}
            eapi_password={{eapi_password}}
            eapi_hostname={{eapi_hostname}}
            eapi_port={{eapi_port}}
