---

#3. Use Ansible to configure your 'primary Ethernet interface' as follows:
#
#switchport mode:        trunk
#trunk native VLAN:      VLAN1
#trunk allowed VLANs:    <the three VLANs created in exercise1>

- name: Exercise3
  hosts: arista

  tasks:
    - name: Set trunk
      eos_switchport: name=Ethernet3 mode=trunk trunk_native_vlan=1 trunk_allowed_vlans=110,120,130
            eapi_username={{eapi_username}}
            eapi_password={{eapi_password}}
            eapi_hostname={{eapi_hostname}}
            eapi_port={{eapi_port}}
            
